import matplotlib.pyplot as plt
import os
import pandas as pd

class ReportGenerator:
    """
    Generates professional performance reports and visualizations.
    """
    def __init__(self, output_dir="outputs/reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_matrix_plots(self, results):
        """
        Creates plots from systematic matrix results.
        Expected results format: list of dicts with [scheduler, steps, batch_size, latency, throughput]
        """
        df = pd.DataFrame(results)
        
        # 1. Throughput vs Batch Size (Grouped by Scheduler)
        plt.figure(figsize=(10, 6))
        for sched in df['scheduler'].unique():
            subset = df[(df['scheduler'] == sched) & (df['steps'] == 30)]
            plt.plot(subset['batch_size'], subset['throughput'], marker='o', label=f"{sched} (30 steps)")
        
        plt.title("DiffusionX: Throughput vs Batch Size")
        plt.xlabel("Batch Size")
        plt.ylabel("Throughput (images/sec)")
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.savefig(os.path.join(self.output_dir, "throughput_scaling.png"))
        plt.close()

        # 2. Latency vs Steps
        plt.figure(figsize=(10, 6))
        for sched in df['scheduler'].unique():
            subset = df[(df['scheduler'] == sched) & (df['batch_size'] == 1)]
            plt.plot(subset['steps'], subset['latency'], marker='s', label=f"{sched} (BS=1)")
            
        plt.title("DiffusionX: Convergence Latency vs Steps")
        plt.xlabel("Inference Steps")
        plt.ylabel("Latency (seconds)")
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.savefig(os.path.join(self.output_dir, "latency_steps.png"))
        plt.close()

    def generate_impact_summary(self, impact_data):
        """
        Generates a markdown summary of optimization impact.
        """
        baseline = impact_data["baseline"]
        opt = impact_data["optimized"]
        improvement = impact_data["latency_improvement"]
        speedup = impact_data["throughput_speedup"]
        
        md_content = f"""# DiffusionX Optimization Impact Report

## 🚀 Performance Overview
| Metric | Baseline | Optimized | Change |
|--------|----------|-----------|--------|
| Latency | {baseline['latency']:.2f}s | {opt['latency']:.2f}s | {improvement:+.1f}% |
| Throughput | {baseline['throughput']:.2f} img/s | {opt['throughput']:.2f} img/s | {speedup:.2f}x speedup |
| Memory (RAM) | {baseline['mem_delta_mb']:.1f} MB | {opt['mem_delta_mb']:.1f} MB | - |

## 🧠 Technical Analysis
- **Optimization Strategy**: Hardware-aware profiling applied.
- **Critical Gain**: {improvement:.1f}% reduction in latency achieved through system-level optimizations.
- **Scalability**: Throughput reached {opt['throughput']:.2f} images per second on current hardware.

---
*Generated by DiffusionX Reporting Engine*
"""
        report_path = os.path.join(self.output_dir, "impact_report.md")
        with open(report_path, "w") as f:
            f.write(md_content)
        
        print(f"[+] Impact report generated at {report_path}")
        return report_path
